// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package myfirstmodule.actions;

import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;

public class JA_Read_Constant_Value extends CustomJavaAction<java.lang.String>
{
	private final java.lang.String ConstantToRead;

	public JA_Read_Constant_Value(
		IContext context,
		java.lang.String _constantToRead
	)
	{
		super(context);
		this.ConstantToRead = _constantToRead;
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		// BEGIN USER CODE
		return Core.getConfiguration().getConstantValue(ConstantToRead).toString();
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "JA_Read_Constant_Value";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
