// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package myfirstmodule.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Set;
import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.core.conf.Configuration;
import com.mendix.logging.ILogNode;

public class JA_Update_Constant extends CustomJavaAction<java.lang.String>
{
	public JA_Update_Constant(IContext context)
	{
		super(context);
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		// BEGIN USER CODE
		final ILogNode logger = Core.getLogger("JavaActionLogger");
		logger.info("Updating constant: " );
		final Configuration conf = Core.getConfiguration();
		final Map<String, Object> configMap = new HashMap<>();
		final Map<String, Long> microflowConstants = new HashMap<>();

		logger.info(conf.getAdminUserName());
		logger.info(conf.getGuestUserRoleName());

		Set<String> constants = Core.getConfiguration().getPublicConstants();
		logger.info("Public constants size is "+constants.size());
		// Log all constants
		logger.info("Fetching all available constants in Mendix:");
		for (String constant : constants) {
			logger.info("constant name "+constant);
		}
//        logger.info(conf.getConstantValue("ConstantToUpdate") != null?conf.getConstantValue("ConstantToUpdate"):"Empty value");

		if (null != conf.getConstantValue("MyFirstModule.Location_Constant") && conf.getConstantValue("MyFirstModule.Location_Constant") != "") {
			logger.info(conf.getConstantValue("MyFirstModule.Location_Constant"));
		} else {
			logger.info("Value is not avilable");
		}
		logger.info("Reading value "+Core.getConfiguration().getConstantValue("MyFirstModule.Location_Constant"));

//		final Configuration confToUpdate = Core.getConfiguration();
		final Map<String, Object> configMapToUpdate = new HashMap<>();
		final Map<String, String> microflowConstantsToUpdate = new HashMap<>();
		microflowConstantsToUpdate.put("MyFirstModule.Location_Constant", "NewValue");
		configMapToUpdate.put("MicroflowConstants", microflowConstantsToUpdate);
//        logger.error( conf1.getConstantValue("Constant"));
		// Apply the update
		Core.getConfiguration().updateConfiguration(configMapToUpdate, true);
		logger.info("Reading new  value "+Core.getConfiguration().getConstantValue("MyFirstModule.Location_Constant"));

		return Core.getConfiguration().getConstantValue("MyFirstModule.Location_Constant").toString();
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "JA_Update_Constant";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
